# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'pc_optimizer_lite.pyside_gui',
        'pc_optimizer_lite.autostart',
        'pc_optimizer_lite.config',
        'pc_optimizer_lite.cpu_optimizer',
        'pc_optimizer_lite.cpu_throttler',
        'pc_optimizer_lite.history_manager',
        'pc_optimizer_lite.monitor',
        'pc_optimizer_lite.notifier',
        'pc_optimizer_lite.optimize_action',
        'pc_optimizer_lite.optimizer',
        'pc_optimizer_lite.pagefile',
        'pc_optimizer_lite.process_safety',
        'pc_optimizer_lite.ram_cleaner',
        'pc_optimizer_lite.sleep_manager',
        'pc_optimizer_lite.smart_process_manager',
        'pc_optimizer_lite.updater',
        'pc_optimizer_lite.version',
        'pc_optimizer_lite.whitelist',
        'plyer.platforms.win.notification',
        'win32gui',
        'win32process',
        'win32com',
        'win32com.client',
        'win32com.client.dynamic',
        'pywintypes',
        'pythoncom',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='PC Optimizer Lite',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['assets\\pc_optimizer_lite.ico'],
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='PC Optimizer Lite',
)
